# Generated by Django 4.0.5 on 2022-06-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(max_length=20)),
                ('curso', models.CharField(max_length=20)),
                ('codigo', models.IntegerField()),
                ('completado', models.BooleanField()),
            ],
        ),
    ]
